#!/usr/bin/env ruby

GENES =<<-EOF
ERBB3
SRCAP
IDH1
SRRM4
LRIG3
E2F7
CACNA1E
DNAH11
SERPINA6
NFAT5
MUC16
MUC17
PTCH1
RYR2
GREB1
LRRC37A3
MYBPC2
LYST
TTN
FGA
TP53
CHAF1B
OR2F1
COL2A1
ASCL3
DYNC1H1
CHD9
CCDC138
DOCK3
SENP6
CSMD1
APOB
COL1A2
GLDN
LILRA3
STX2
RAI1
RYR1
IDH2
COL5A3
LRRTM3
OR4C46
TRPC4
SH3GL3
SIPA1L3
LAMB3
USH2A
GPR98
HSPA12B
EIF2AK3
TRIM2
TNKS
ALMS1
DGKD
LRP1B
ZNF677
SETD2
PPP4R4
PCLO
PDGFRL
BLNK
MDH2
EOF
genes = GENES.split("\n")

FORMATS =<<-EOF
Ensembl Gene ID
Associated Gene Name
UniProt/SwissProt Accession
Entrez Gene ID
EOF
formats = FORMATS.split("\n")

require 'rbbt/workflow'

Workflow.require_workflow "Translation"

jobs = []
formats.each do |format|
  Organism.organism_codes.each do |organism|
      jobs << Translation.job(:translate, "BOOTSTRAP-#{organism}", :genes => genes.dup, :organism => organism, :format => format)
  end
end

jobs.shuffle!
procs = ARGV.shift 
require 'rbbt/util/semaphore'
Misc.bootstrap(jobs, procs) do |job|
  job.run
end

